name: HAC_env
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - numpy=1.25.5
  - plyfile=0.8.1
  - tqdm
  - ninja
  - pip:
      - einops
      - wandb==0.16.4
      - lpips
      - torchac
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/gridencoder
